### ISSUE TITLE
SINTESIS

### ISSUE THREAD

**Issue by IMA-G** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-IMA-G#1]

**Comment by IMA-G** [comment]
[Síntesis.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-IMA-G/files/9569302/Sintesis.pdf)

**Comment by carlos-chrs** [comment]
Revisado 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
